site_name: spotDL GNOME
site_description: Native GNOME desktop app for downloading music from Spotify
site_author: loafdaddy
site_url: "https://github.com/loafdaddy/spotDL-GNOME"
repo_url: "https://github.com/loafdaddy/spotDL-GNOME"
repo_name: "loafdaddy/spotDL-GNOME"
site_dir: "site"

nav:
- Home: index.md
- Docs index: README.md
- Setup: SETUP.md
- Configuration: CONFIGURATION.md
- FAQ: FAQ.md
- Architecture: ARCHITECTURE.md
- Usage:
  - Usage examples: usage.md
  - Troubleshooting: troubleshooting.md
  - CLI installation notes: installation.md
- Development:
  - Development: DEVELOPMENT.md
  - Contributing: CONTRIBUTING.md
  - Code Of Conduct: CODE_OF_CONDUCT.md
  - Releases: RELEASES.md
  - Roadmap: ROADMAP.md
  - TODO: TODO.md
- Code Reference: reference/

theme:
  name: material
  features:
    - content.code.annotate
    - navigation.tabs
    - navigation.top
    - toc.integrate

  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: green
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: light green
    toggle:
      icon: material/weather-night
      name: Switch to light mode

plugins:
- gen-files:
    scripts:
    - scripts/docs/gen_ref_nav.py
- search
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_options:
            ignore_init_summary: yes
          merge_init_into_class: yes
          show_submodules: no

markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.tasklist
- pymdownx.superfences
- pymdownx.snippets:
    check_paths: true
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.highlight:
    use_pygments: true
    pygments_lang_class: true
- toc:
    permalink: "¤"

watch:
- spotdl
